/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import Cadastros.CadMestre;
import Cadastros.CadastroMestreArquivo;
import Entidades.Mestre;
import Exception.NomeUsuarioDuplicadoException;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class CadastroMestre extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMestre
     */
    
    private CadMestre cad;
    private CadastroMestreArquivo dao;
    
    public CadastroMestre() {
        ImageIcon logo = new ImageIcon("src/imagens/logo.jpg");
        setIconImage(logo.getImage());
        initComponents();
        
    }
    
    public CadastroMestre (CadastroMestreArquivo cad){
        ImageIcon logo = new ImageIcon("src/imagens/logo.jpg");
        setIconImage(logo.getImage());
        initComponents();
        this.dao = cad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        nomePrincipal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mestre = new javax.swing.JLabel();
        campoMestre = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        senha2 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();
        campoSenha2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Mestre");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(java.awt.Color.white);

        nomePrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomePrincipal.setForeground(new java.awt.Color(153, 0, 0));
        nomePrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePrincipal.setText("Cadastro de Mestre");

        mestre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mestre.setForeground(new java.awt.Color(153, 0, 0));
        mestre.setText("Nome do Mestre");

        usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(153, 0, 0));
        usuario.setText("Usuario");

        senha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        senha.setForeground(new java.awt.Color(153, 0, 0));
        senha.setText("Senha");

        senha2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        senha2.setForeground(new java.awt.Color(153, 0, 0));
        senha2.setText("Repetir Senha");

        salvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salvar.setForeground(new java.awt.Color(153, 0, 0));
        salvar.setText("Salvar");
        salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        campoSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenha2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(nomePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mestre)
                            .addComponent(usuario)
                            .addComponent(senha)
                            .addComponent(senha2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoUsuario)
                            .addComponent(campoMestre)
                            .addComponent(campoSenha)
                            .addComponent(campoSenha2))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nomePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mestre)
                    .addComponent(campoMestre))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha2)
                    .addComponent(campoSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salvar)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        
        String nomeMestre = campoMestre.getText();
        String nomeUsuario = campoUsuario.getText();
        String senha = campoSenha.getText();
        String senha2 = campoSenha2.getText();
        if (!senha.equals(senha2)){
            JOptionPane.showMessageDialog(null, "Senhas Diferentes",
                    "Mensagem de Erro", JOptionPane.ERROR_MESSAGE);
            campoSenha.setText("");
            campoSenha2.setText("");
        } else {
            try {
                Mestre m = new Mestre (nomeUsuario, senha);
                if(dao.adicionar(m) && !"".equals(campoUsuario.getText()) && !"".equals(campoSenha.getText())){
                    JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso");
                    LoginMestre novo = new LoginMestre();
                    novo.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao Salvar",
                    "Mensagem de Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException | ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de Erro !", JOptionPane.ERROR_MESSAGE);
            } catch (NomeUsuarioDuplicadoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Mensagem de Erro !", JOptionPane.ERROR_MESSAGE);
                campoUsuario.setText("");
                campoMestre.setText("");
                campoSenha.setText("");
                campoSenha2.setText("");
            }
        }
        
    }//GEN-LAST:event_salvarActionPerformed

    private void campoSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenha2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMestre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoMestre;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JPasswordField campoSenha2;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mestre;
    private javax.swing.JLabel nomePrincipal;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel senha2;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
